/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:3ec3d90a-085b-4910-b4e7-9fdc9ff1a033",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_Y4joK4BYr",
    "aws_user_pools_web_client_id": "53l215ivd40ofer7bv4sinmpbo",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://au6v2etbjfgdzcyld44y2wqhxm.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-jowoaduc5nchdpienpcpals7ae",
    "aws_user_files_s3_bucket": "angularef187cb0184c443f9f4a1ec547ae89229af85-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
